"""Voice packs for the site: catalogue, previews and hosted zips.

Reads a checkout of edgetx-sdcard-sounds (env EDGETX_VOICES_SRC, default ../edgetx-sdcard-sounds).
In CI that checkout is a sparse partial clone; `python voices_build.py --sparse-patterns` prints
what it must contain.

site/data/voices.json      catalogue: languages, voices, preview phrases, texts
site/audio/<hash>.mp3      preview clips (all voices) and every phrase (hosted voices)
(single-file downloads link to the raw files in the voice repository; the bundle builder
 works from the zip, so nothing is stored twice)
site/dl/voice-<id>.flac.zip  voice packs we host: SOUNDS/<lang>/*.flac (16 kHz, lossless, stored).
                            The browser decodes them back to WAV when you download (assets/voicepack.js),
                            which keeps ~40 voices under the Pages size limit.
"""
import wave
import csv
import hashlib
import json
import os
import shutil
import subprocess
import sys
import threading
import time
import urllib.request
import zipfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = Path(os.environ.get("EDGETX_VOICES_SRC", ROOT.parent / "edgetx-sdcard-sounds")).expanduser()
RELEASE_REPO = "EdgeTX/edgetx-sdcard-sounds"
RELEASE_TAG = "v2.12.3"          # fallback when the GitHub API is unreachable
FORK = "HansF/edgetx-sdcard-sounds"

# The phrases every voice card lets you hear (file relative to SOUNDS/<lang>/, without .wav).
PREVIEWS = ["SYSTEM/hello", "armed", "disarm", "lowbat", "clobat", "SYSTEM/telemko", "SYSTEM/telemok",
            "SYSTEM/rssi_red", "SYSTEM/thralert", "fm-1", "rth", "ready", "takeof", "landin",
            "SYSTEM/0012", "SYSTEM/0173", "SYSTEM/volt1", "SYSTEM/percent1", "SYSTEM/0003", "SYSTEM/minute1"]

# dir -> (language code, language, native name, flag, voice name, gender, engine, csv stem, hosted, note)
# hosted voices are generated by this project with ElevenLabs and served from the site;
# the others are the official EdgeTX packs, linked to the EdgeTX release.
VOICES = {
    "nl":            ("nl-BE", "Dutch",              "Nederlands (Vlaams)", "🇧🇪", "Hans",      "m", "ElevenLabs", "nl-NL", True,  "Flemish narrator, calm and warm. Made for this site; EdgeTX has no Dutch pack."),
    "nl-emma":       ("nl-NL", "Dutch",              "Nederlands",          "🇳🇱", "Emma",      "f", "ElevenLabs", "nl-NL", True,  "Standard Dutch, clear and confident."),
    "nl-petra":      ("nl-BE", "Dutch",              "Nederlands (Vlaams)", "🇧🇪", "Petra",     "f", "ElevenLabs", "nl-NL", True,  "Flemish, energetic and clear. Vlaamse stem voor je zender."),
    "en_gb-daniel":  ("en-GB", "English",            "English (UK)",        "🇬🇧", "Daniel",    "m", "ElevenLabs", "en-GB", True,  "Steady broadcaster. The most natural English pack here."),
    "en_au-arabella": ("en-AU", "English",           "English (Australia)", "🇦🇺", "Arabella",  "f", "ElevenLabs", "en-US", True,  "Australian, bright and friendly. G'day from the flight line."),
    "en_sc-adam":    ("en-GB", "English",            "English (Scotland)",  "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Adam",      "m", "ElevenLabs", "en-GB", True,  "Classic Scottish storyteller. Low battery never sounded this dignified."),
    "en_ie-patrick": ("en-IE", "English",            "English (Ireland)",   "🇮🇪", "Patrick",   "m", "ElevenLabs", "en-GB", True,  "Irish, engaging and warm. Grand, so."),
    "de_ch-peter":   ("de-CH", "German",             "Deutsch (Schweiz)",   "🇨🇭", "Peter",     "m", "ElevenLabs", "de-DE", True,  "Swiss German, clear and professional. Schweizerdeutsch gefärbt, hochdeutsch gesprochen."),
    "fr_be-christophe": ("fr-BE", "French",          "Français (Belgique)", "🇧🇪", "Christophe", "m", "ElevenLabs", "fr-FR", True, "Belgian French, soft narrator. Une voix belge pour ta radio."),
    "fr_ca-danielle": ("fr-CA", "French",            "Français (Québec)",   "🇨🇦", "Danielle",  "f", "ElevenLabs", "fr-FR", True,  "Québécois, gentle and engaging. Une voix d'ici."),
    "es_mx-enrique": ("es-MX", "Spanish",            "Español (México)",    "🇲🇽", "Enrique",   "m", "ElevenLabs", "es-ES", True,  "Mexican Spanish, credible and rich. Una voz mexicana para tu radio."),
    "en_gb-alice":   ("en-GB", "English",            "English (UK)",        "🇬🇧", "Alice",     "f", "ElevenLabs", "en-GB", True,  "Clear, engaging British female. Every number lands."),
    # Funny: character voice packs. Numbers and flight modes stay plain English; only ~55 event
    # phrases (armed, low battery, RTH...) get the character's lines, so the joke survives 50 flights.
    "en_fun-pit-crew":      ("en-GB", "English", "English (UK)", "🇬🇧", "Pit Crew Chief",    "m", "ElevenLabs", "en-fun-pit-crew",      True, "Cyberpunk pit crew. Clipped, technical, a little too excited about voltage."),
    "en_fun-fighter-pilot": ("en-GB", "English", "English (UK)", "🇬🇧", "Fighter Pilot",     "m", "ElevenLabs", "en-fun-fighter-pilot", True, "Overconfident 80s action hero. Every flight is a mission."),
    "en_fun-butler":        ("en-GB", "English", "English (UK)", "🇬🇧", "The Butler",        "m", "ElevenLabs", "en-fun-butler",        True, "Extremely British. Disarming the model is announced the way one announces dinner."),
    "en_fun-race-engineer": ("en-GB", "English", "English (UK)", "🇬🇧", "Race Engineer",     "m", "ElevenLabs", "en-fun-race-engineer", True, "Unhinged pit-wall radio. BOX BOX BOX! (for a battery warning.)"),
    "en_fun-arcade":        ("en-GB", "English", "English (UK)", "🇬🇧", "Arcade Announcer",  "m", "ElevenLabs", "en-fun-arcade",        True, "Retro arcade cabinet. ROUND ONE... FLY! Low battery is WASTED."),
    "pt_pt-paulo":   ("pt-PT", "Portuguese",         "Português (Portugal)", "🇵🇹", "Paulo",    "m", "ElevenLabs", "pt-PT", True,  "European Portuguese, diplomatic and friendly. The official pack is Brazilian; this one is from Portugal."),
    "de-otto":       ("de-DE", "German",             "Deutsch",             "🇩🇪", "Otto",      "m", "ElevenLabs", "de-DE", True,  "Casual, natural German male. Endlich eine Männerstimme."),
    "fr-martin":     ("fr-FR", "French",             "Français",            "🇫🇷", "Martin",    "m", "ElevenLabs", "fr-FR", True,  "Deep, warm French male. Une voix grave pour la radio."),
    "it-marcotrox":  ("it-IT", "Italian",            "Italiano",            "🇮🇹", "Marco",     "m", "ElevenLabs", "it-IT", True,  "Warm, balanced Italian male. Finalmente una voce maschile."),
    "cz-adam":       ("cs-CZ", "Czech",              "Čeština",             "🇨🇿", "Adam",      "m", "ElevenLabs", "cs-CZ", True,  "Velvety, conversational Czech male."),
    "ru-nikolay":    ("ru-RU", "Russian",            "Русский",             "🇷🇺", "Nikolay",   "m", "ElevenLabs", "ru-RU", True,  "Confident, clear Russian male."),
    "en":            ("en-IE", "English",            "English (Ireland)",   "🇮🇪", "Emily",     "f", "Azure neural", "en-GB", False, "The EdgeTX default voice."),
    "en_gb-libby":   ("en-GB", "English",            "English (UK)",        "🇬🇧", "Libby",     "f", "Azure neural", "en-GB", False, ""),
    "en_gb-ryan":    ("en-GB", "English",            "English (UK)",        "🇬🇧", "Ryan",      "m", "Azure neural", "en-GB", False, ""),
    "en_gb-glados":  ("en-GB", "English",            "English (UK)",        "🇬🇧", "GLaDOS",    "x", "Synth",        "en-GB", False, "A passive-aggressive lab computer. You know the one."),
    "en_us-guy":     ("en-US", "English",            "English (US)",        "🇺🇸", "Guy",       "m", "Azure neural", "en-US", False, ""),
    "en_us-michelle": ("en-US", "English",           "English (US)",        "🇺🇸", "Michelle",  "f", "Azure neural", "en-US", False, ""),
    "en_us-sara":    ("en-US", "English",            "English (US)",        "🇺🇸", "Sara",      "f", "Azure neural", "en-US", False, ""),
    "en_us-joshua-bardwell": ("en-US", "English",    "English (US)",        "🇺🇸", "Joshua Bardwell", "m", "Human recording", "en-US", False, "Recorded by the FPV YouTuber himself."),
    "de":            ("de-DE", "German",             "Deutsch",             "🇩🇪", "Katja",     "f", "Azure neural", "de-DE", False, ""),
    "fr":            ("fr-FR", "French",             "Français",            "🇫🇷", "Denise",    "f", "Azure neural", "fr-FR", False, ""),
    "es":            ("es-ES", "Spanish",            "Español",             "🇪🇸", "Elvira",    "f", "Azure neural", "es-ES", False, ""),
    "es_cl-catalina": ("es-CL", "Spanish",           "Español (Chile)",     "🇨🇱", "Catalina",  "f", "Azure neural", "es-CL", False, ""),
    "it":            ("it-IT", "Italian",            "Italiano",            "🇮🇹", "Elsa",      "f", "Azure neural", "it-IT", False, ""),
    "pt":            ("pt-BR", "Portuguese",         "Português (Brasil)",  "🇧🇷", "Francisca", "f", "Azure neural", "pt-PT", False, ""),
    "pl":            ("pl-PL", "Polish",             "Polski",              "🇵🇱", "Sarah",     "f", "ElevenLabs",   "pl-PL", False, ""),
    "cz":            ("cs-CZ", "Czech",              "Čeština",             "🇨🇿", "Vlasta",    "f", "Azure neural", "cs-CZ", False, ""),
    "da":            ("da-DK", "Danish",             "Dansk",               "🇩🇰", "Christel",  "f", "Azure neural", "da_DK", False, ""),
    "se":            ("sv-SE", "Swedish",            "Svenska",             "🇸🇪", "Sofie",     "f", "Azure neural", "sv-SE", False, ""),
    "ru":            ("ru-RU", "Russian",            "Русский",             "🇷🇺", "Svetlana",  "f", "Azure neural", "ru-RU", False, ""),
    "ua-ostap":      ("uk-UA", "Ukrainian",          "Українська",          "🇺🇦", "Ostap",     "m", "Azure neural", "uk-UA", False, ""),
    "ua-polina":     ("uk-UA", "Ukrainian",          "Українська",          "🇺🇦", "Polina",    "f", "Azure neural", "uk-UA", False, ""),
    "jp":            ("ja-JP", "Japanese",           "日本語",               "🇯🇵", "Nanami",    "f", "Azure neural", "ja-JP", False, ""),
    "ko":            ("ko-KR", "Korean",             "한국어",               "🇰🇷", "Wavenet B", "f", "Google neural", "ko-KR", False, ""),
    "cn":            ("zh-CN", "Chinese",            "中文（简体）",          "🇨🇳", "Xiaoxiao",  "f", "Azure neural", "zh-CN", False, ""),
    "tw":            ("zh-TW", "Chinese",            "中文（台灣）",          "🇹🇼", "HsiaoChen", "f", "Azure neural", "zh-TW", False, ""),
    "hk":            ("zh-HK", "Cantonese",          "廣東話",               "🇭🇰", "HiuGaai",   "f", "Azure neural", "zh-HK", False, ""),
}

# Official packs we redistribute (as FLAC) so the mixer can bundle them. GLaDOS is a game character
# and Joshua Bardwell's is a real person's recording: both stay linked to the EdgeTX release.
NOT_PACKED = {"en_gb-glados", "en_us-joshua-bardwell"}


def packed(d):
    return VOICES[d][8] or d not in NOT_PACKED


README_OFFICIAL = """{name} - EdgeTX voice pack ({native})
Official EdgeTX voice pack ({engine}), from https://github.com/EdgeTX/edgetx-sdcard-sounds (GPL-2.0).
Repackaged by Stickbeats; audio is unchanged apart from 16 kHz resampling where the original was higher.

INSTALL
1. Connect the radio in USB storage mode (or take the SD card out).
2. Copy the SOUNDS folder from this zip onto the root of the SD card.
3. On the radio: Radio setup -> Voice language -> {language}. Power-cycle.

{n} files.

Want game-style alert sounds on top of this voice? https://rotordeck.com/stickbeats/
"""

README = """{name} - EdgeTX voice pack ({native})
Generated with ElevenLabs by Stickbeats. {note}
Free audio: CC0 1.0 Universal (public domain dedication).
https://creativecommons.org/publicdomain/zero/1.0/

INSTALL
1. Connect the radio in USB storage mode (or take the SD card out).
2. Copy the SOUNDS folder from this zip onto the root of the SD card.
3. On the radio: Radio setup -> Voice language -> {language}. Power-cycle.

{n} files, 16 kHz mono 16-bit WAV. Numbers, units, alarms and every callout EdgeTX
knows, plus the Betaflight, iNav and Yaapu script phrases in SOUNDS/{lang}/SCRIPTS.

Want game-style alert sounds on top of this voice? https://rotordeck.com/stickbeats/
"""


def sparse_patterns():
    pats = ["/voices/*.csv", "/sounds.json", "/SOUNDS/*/.elevenlabs.json"]
    for f in PREVIEWS:
        pats.append(f"/SOUNDS/*/{f}.wav")
    for d in VOICES:
        if packed(d):
            pats.append(f"/SOUNDS/{d}/**")
    return pats


def _hash(p: Path):
    return hashlib.sha1(p.read_bytes()).hexdigest()[:16]


def _mp3(args):
    wav, mp3 = args
    if mp3.exists():
        return
    cached = MP3_CACHE / mp3.name          # content-hash named, survives site_build pruning and CI runs
    if not cached.exists():
        MP3_CACHE.mkdir(exist_ok=True)
        tmp = cached.with_name(f"{cached.stem}.{threading.get_ident()}.tmp")
        subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(wav),
                        "-ac", "1", "-ar", "32000", "-b:a", "48k", "-f", "mp3", str(tmp)], check=True)
        tmp.replace(cached)
    shutil.copyfile(cached, mp3)


FLAC_CACHE = ROOT / ".flac-cache"
MP3_CACHE = ROOT / ".mp3-cache"
PACK_RATE = 16000


def _rate(wav: Path) -> int:
    try:
        with wave.open(str(wav)) as w:
            return w.getframerate()
    except (wave.Error, EOFError):      # a few official "wav" files are MP3 in disguise
        out = subprocess.run(["ffprobe", "-v", "error", "-select_streams", "a:0", "-show_entries",
                              "stream=sample_rate", "-of", "csv=p=0", str(wav)], capture_output=True, text=True).stdout
        return int(out.strip() or PACK_RATE)


def _strip_flac(data: bytes) -> bytes:
    """Keep only STREAMINFO: ffmpeg adds 8 KB of padding and a comment block, a quarter of a short clip."""
    i, blocks = 4, []
    while True:
        h = data[i]
        n = int.from_bytes(data[i + 1:i + 4], "big")
        blocks.append((h & 127, data[i + 4:i + 4 + n]))
        i += 4 + n
        if h & 128:
            break
    info = next(b for t, b in blocks if t == 0)
    return data[:4] + bytes([0x80]) + len(info).to_bytes(3, "big") + info + data[i:]


def _flac(wav: Path) -> Path:
    """Lossless 16-bit FLAC, resampled to 16 kHz when the source is higher (like the official packs)."""
    out = FLAC_CACHE / f"{_hash(wav)}.flac"
    if not out.exists():
        FLAC_CACHE.mkdir(exist_ok=True)
        tmp = out.with_name(f"{out.stem}.{threading.get_ident()}.tmp")     # identical clips race otherwise
        ar = ["-ar", str(PACK_RATE)] if _rate(wav) > PACK_RATE else []
        subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(wav), *ar,
                        "-sample_fmt", "s16", "-compression_level", "8", "-f", "flac", str(tmp)], check=True)
        tmp.write_bytes(_strip_flac(tmp.read_bytes()))
        tmp.replace(out)
    return out


def _zip_stored(path, files):
    tmp = path.with_suffix(".tmp")
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_STORED) as z:     # FLAC does not compress further
        for arc, src in files:
            zi = zipfile.ZipInfo(arc, date_time=(2026, 1, 1, 0, 0, 0))
            zi.compress_type = zipfile.ZIP_STORED
            z.writestr(zi, src if isinstance(src, (bytes, str)) else src.read_bytes())
    tmp.replace(path)


def _dur(wav: Path) -> float:
    out = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(wav)],
                         capture_output=True, text=True).stdout.strip()
    return float(out or 0)


def read_csv(stem: str, scripts=False):
    """file (relative, no .wav) -> (translation, english)"""
    p = SRC / "voices" / f"{stem}{'_scripts' if scripts else ''}.csv"
    out = {}
    if not p.exists():
        return out
    with p.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            fn = (row.get("Filename") or "").strip()
            if not fn:
                continue
            rel = ("SCRIPTS/" if scripts else "") + ((row.get("Path") or "").strip() + "/" if (row.get("Path") or "").strip() else "") + fn[:-4]
            out[rel] = ((row.get("Translation") or "").strip(), (row.get("Source text") or "").strip())
    return out


def release_assets():
    """name -> (url, size) for the latest official EdgeTX voice release."""
    try:
        req = urllib.request.Request(f"https://api.github.com/repos/{RELEASE_REPO}/releases/latest",
                                     headers={"Accept": "application/vnd.github+json", "User-Agent": "stickbeats"})
        with urllib.request.urlopen(req, timeout=20) as r:
            d = json.load(r)
        return d["tag_name"], {a["name"]: (a["browser_download_url"], a["size"]) for a in d["assets"]}
    except Exception as exc:  # noqa: BLE001
        print(f"voices: GitHub API unavailable ({exc}); using {RELEASE_TAG} URLs without sizes")
        v = RELEASE_TAG.lstrip("v")
        return RELEASE_TAG, {f"edgetx-sdcard-sounds-{d}-{v}.zip":
                             (f"https://github.com/{RELEASE_REPO}/releases/download/{RELEASE_TAG}/edgetx-sdcard-sounds-{d}-{v}.zip", 0)
                             for d in VOICES}


def _zip(path, files):
    tmp = path.with_suffix(".tmp")
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as z:
        for arc, src in files:
            zi = zipfile.ZipInfo(arc, date_time=(2026, 1, 1, 0, 0, 0))
            zi.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(zi, src if isinstance(src, (bytes, str)) else src.read_bytes())
    tmp.replace(path)


def build_voices(site: Path):
    t0 = time.time()
    sounds = SRC / "SOUNDS"
    if not sounds.is_dir():
        print(f"voices: {SRC} not found, skipping voice packs (set EDGETX_VOICES_SRC)")
        return None
    for sub in ("data", "audio", "wav", "dl"):
        (site / sub).mkdir(parents=True, exist_ok=True)
    for old in (site / "dl").glob("voice-*.zip"):      # superseded by voice-<id>.flac.zip
        if not old.name.endswith(".flac.zip"):
            old.unlink()
    tag, assets = release_assets()
    ver = tag.lstrip("v")
    en_main, en_scripts = read_csv("en-GB"), read_csv("en-GB", True)
    english = {**en_main, **en_scripts}
    jobs, voices, packs = {}, [], []
    for d, (code, language, native, flag, name, gender, engine, stem, hosted, note) in VOICES.items():
        root = sounds / d
        if not root.is_dir():
            continue
        texts = {**read_csv(stem), **read_csv(stem, True)}
        wavs = sorted(p for p in root.rglob("*.wav"))
        rels = [str(p.relative_to(root))[:-4].replace("\\", "/") for p in wavs]
        clips, durs = {}, {}
        want = set(PREVIEWS) if not hosted else set(rels)
        for p, rel in zip(wavs, rels):
            if rel not in want:
                continue
            h = _hash(p)
            clips[rel] = h
            jobs[h] = (p, site / "audio" / f"{h}.mp3")
        durs = {rel: None for rel in clips}   # filled after the pool below
        entry = dict(id=d, code=code, lang=code[:2], language=language, native=native, flag=flag, name=name,
                     gender=gender, engine=engine, hosted=hosted, note=note, files=len(wavs),
                     clips=clips, durs=durs, funny=d.startswith("en_fun-"),
                     texts={rel: texts.get(rel, ("", ""))[0] for rel in clips},
                     previews=[f for f in PREVIEWS if f in clips])
        if hosted:
            manifest = root / ".elevenlabs.json"
            checks = json.loads(manifest.read_text()) if manifest.exists() else {}
            entry.update(verified=sum(1 for v in checks.values() if v.get("stt_ok")), checked=len(checks),
                         source=f"https://github.com/{FORK}/tree/main/SOUNDS/{d}",
                         raw=f"https://raw.githubusercontent.com/{FORK}/main/SOUNDS/{d}/")
        else:
            url, size = assets.get(f"edgetx-sdcard-sounds-{d}-{ver}.zip", ("", 0))
            entry.update(zip=url, zipSize=size, source=f"https://github.com/{RELEASE_REPO}")
        if packed(d):
            packs.append((d, entry, root, wavs, rels, d[:2]))
        voices.append(entry)
    with ThreadPoolExecutor(8) as ex:
        for d, entry, root, wavs, rels, lang in packs:
            flacs = list(ex.map(_flac, wavs))
            tpl = README if entry["hosted"] else README_OFFICIAL
            readme = tpl.format(name=entry["name"], native=entry["native"], note=entry["note"], engine=entry["engine"],
                                language=entry["language"], n=len(wavs), lang=lang)
            path = site / "dl" / f"voice-{d}.flac.zip"
            _zip_stored(path, [(f"SOUNDS/{lang}/{rel}.flac", f) for f, rel in zip(flacs, rels)] + [("README.txt", readme)])
            entry.update(pack=f"dl/voice-{d}.flac.zip", packSize=path.stat().st_size)
            if entry["hosted"]:
                entry.update(zip=entry["pack"], zipSize=entry["packSize"])
        list(ex.map(_mp3, jobs.values()))
        durations = dict(zip(jobs, ex.map(lambda j: round(_dur(j[0]), 2), jobs.values())))
    for v in voices:
        v["durs"] = {rel: durations[h] for rel, h in v["clips"].items()}
    order = {k: i for i, k in enumerate(VOICES)}
    voices.sort(key=lambda v: order[v["id"]])
    languages = []
    for v in voices:
        if not any(l["lang"] == v["lang"] for l in languages):
            languages.append({"lang": v["lang"], "language": v["language"], "flag": v["flag"]})
    data = {
        "generated": time.strftime("%Y-%m-%d"),
        "release": {"tag": tag, "url": f"https://github.com/{RELEASE_REPO}/releases/tag/{tag}"},
        "previews": [{"file": f, "en": english.get(f, ("", f))[1] or english.get(f, ("", f))[0]} for f in PREVIEWS],
        "english": {k: v[1] or v[0] for k, v in english.items()},
        "languages": languages,
        "voices": voices,
    }
    (site / "data" / "voices.json").write_text(json.dumps(data, separators=(",", ":"), ensure_ascii=False))
    write_static_pages(site, data)
    hosted = [v for v in voices if v["hosted"]]
    hosted_packs = [v for v in voices if v.get("pack")]
    print(f"voices: {len(voices)} voices in {len(languages)} languages, {len(hosted)} made by Stickbeats, "
          f"{len(hosted_packs)} hosted ({sum(v['packSize'] for v in hosted_packs) / 1e6:.0f} MB of FLAC zips), {len(jobs)} clips, {time.time() - t0:.1f}s")
    return data


SITE_URL = "https://rotordeck.com/stickbeats/"


def write_static_pages(site: Path, data):
    """One crawlable page per voice (site/v/<id>.html) plus sitemap.xml.

    voice.html renders everything client-side, which search engines index poorly. The static
    copies carry a real title, description, heading and the phrase list as text, then the same
    script takes over for playback. Also the place where "EdgeTX Vlaamse stem" gets to rank.
    """
    tpl = (site / "voice.html").read_text()
    (site / "v").mkdir(exist_ok=True)
    urls = [SITE_URL, SITE_URL + "voices.html", SITE_URL + "install.html", SITE_URL + "request.html", SITE_URL + "mix.html", SITE_URL + "compare.html"]
    import html as H
    for v in data["voices"]:
        g = {"m": "male", "f": "female"}.get(v["gender"], "synthetic")
        title = f"{v['name']} · {v['native']} EdgeTX voice pack ({g}) · Stickbeats"
        kind = "Free CC0 voice pack made by Stickbeats" if v["hosted"] else "Official EdgeTX voice pack"
        desc = (f"{v['language']} ({v['native']}) voice pack for EdgeTX radios: {v['name']}, {g}, {v['engine']}. "
                f"{v['note']} Listen to every phrase, then download SOUNDS/{v['lang']} for your SD card.").replace("  ", " ")
        phrases = sorted(v["texts"].items())
        lines = "".join(f"<li>{H.escape(t or data['english'].get(f, f))}</li>" for f, t in phrases if (t or data["english"].get(f)))
        seo = (f'<div id="seo"><h1>{v["flag"]} {H.escape(v["name"])}: {H.escape(v["native"])} voice pack for EdgeTX</h1>'
               f'<p>{H.escape(desc)}</p><p>{kind}. {v["files"]} files.</p>'
               f'<h2>{len(phrases)} phrases</h2><ul>{lines}</ul></div>')
        page = tpl.replace("<title>Voice · Stickbeats</title>",
                           f'<title>{H.escape(title)}</title>\n<meta name="description" content="{H.escape(desc)}">'
                           f'\n<meta property="og:title" content="{H.escape(title)}"><meta property="og:description" content="{H.escape(desc)}">'
                           f'\n<link rel="canonical" href="{SITE_URL}v/{v["id"]}.html"><base href="../">'
                           f'\n<script>window.SB_VOICE="{v["id"]}"</script>')
        page = page.replace('<section class="v-hero">', seo + '\n  <section class="v-hero">', 1)
        (site / "v" / f"{v['id']}.html").write_text(page)
        urls.append(f"{SITE_URL}v/{v['id']}.html")
    urls += [f"{SITE_URL}theme.html?t={t}" for t in sorted(p.stem for p in (site / "dl").glob("*.zip") if not p.stem.endswith("-midi") and not p.stem.startswith("voice-") and p.stem != "all-themes")]
    (site / "sitemap.xml").write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
                                      + "".join(f"  <url><loc>{H.escape(u)}</loc></url>\n" for u in urls) + "</urlset>\n")
    (site / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {SITE_URL}sitemap.xml\n")


if __name__ == "__main__":
    if "--sparse-patterns" in sys.argv:
        print("\n".join(sparse_patterns()))
    else:
        build_voices(ROOT / "site")
